### ISSUE TITLE
Please Use Latest Innovus Commands

### ISSUE THREAD

**Issue by idwwwoqq808** [ucb-bar/hammer-cadence-plugins#82]
In the [__init__.py](https://github.com/ucb-bar/hammer-cadence-plugins/blob/80f0e276cf6a358f6d38288f5f69ccac41ea22ca/par/innovus/__init__.py#L925) file for Innovus, I found some tcl commands out dated.
I'm using Innovus 18.10, and I'm comparing the python file with the Innovus Text Command Reference.

On line 886, the command "plan_design" is replaced by "planDesign". 
The command "create_place_halo" on line 891 and "create_route_halo" on line 893 do not exist in the reference.

I don't know if those commands still work for recent Innovus versions.

**Comment by jagjordi** [comment]
`plan_design` is the new [Stylus UI](https://www.cadence.com/ko_KR/home/company/events/webinars/introduction-to-the-stylus-common-ui-for-digital-implementation.html), `planDesign` is the legacy command format

**Comment by idwwwoqq808** [comment]
> `plan_design` is the new [Stylus UI](https://www.cadence.com/ko_KR/home/company/events/webinars/introduction-to-the-stylus-common-ui-for-digital-implementation.html), `planDesign` is the legacy command format


Oh, I see. Do you know innovus uses stylus UI starting from which version?

**Comment by edwardcwang** [comment]
Common UI/Stylus UI has been the recommended path for at least 5 years now if not more.

**Comment by jagjordi** [comment]
You need to launch innovus like this `innovus -stylus` to enable it.

**Comment by idwwwoqq808** [comment]
> 



> You need to launch innovus like this `innovus -stylus` to enable it.

I got it. Thank you so much.
