### ISSUE TITLE
Powerring for non-flipchip design

### ISSUE THREAD

**Issue by bkoppelmann** [ucb-bar/hammer-cadence-plugins#85]
Hi,

I'm doing a flat design with pads around the chip and I wanted to add a power ring. However during floorplaning the innovus plugin uses [`-core_margins_by die` ](https://github.com/ucb-bar/hammer-cadence-plugins/blob/db628a0c6c1bdc2045359f70c82f31f68c5cc0a5/par/innovus/__init__.py#L913) instead of `-core_margins_by io`. I'd rather not override the `floorplan_design` step for such a small change. 

I see two ways to fix this:
- Add a IR for Innovus that lets me specify whether I want `io` or `die`.
- Make `floorplan_design` into substeps such that I can just override the step that generates the `create_floorplan` TCL command

What do you guys prefer?

Cheers,
Bastian

**Comment by harrisonliew** [comment]
Bastian,

`-core_margins_by_die` only means that the margin you specify must also include the width of the IO ring that you use. Doing this also ensures that the core dimension isn't fully linked to the IO cells/ring as would be if  `-core_margins_by_io` is used. Furthermore, I don't see how power rings are dependent on the margin specification type. If you specify rings of `-type core_rings`, the rings go around the core area, and as long as your floorplan margins are larger than IO ring + power ring width, it will work.

Methodology-wise, for IO rings, we use the IO file methodology and insert them after the floorplan is created. This sufficiently decouples the steps for us and allows for floorplan exploration even if the IO ring implementation isn't finished.

If you really still want to use `-core_margins_by_io`, I would suggest making a replacement hook for the `create_floorplan` step. You can learn how to write hooks here: http://docs.hammer-eda.org/en/latest/Hammer-Use/Hooks.html with an example driver file here: https://github.com/ucb-bar/chipyard/blob/main/vlsi/example-vlsi

**Comment by harrisonliew** [comment]
> Just to clarify, by IO file methodology you mean specifying the IO ring in an IO file and loading it with read_io_file?

Correct. We are working on some supporting scripts to generate IO files, but it may not be done in time for your use, so you will need to write yours manually.

**Comment by bkoppelmann** [comment]
Thanks again!
